{
 "title": "media-stack",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Linux Distro",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"linux_distro\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Platform",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "targets": [
    {
     "query": "    from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"platform\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "targets": [
    {
     "query": "    from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"os_version\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "description": "Total CPU Cores",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpucore\")  // Filter for the specific field"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -30s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"containers\")\r\n  |> count()\r\n"
    }
   ]
  },
  { "title": "System State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "iowait",
   "type": "gauge",
   "description": "iowait: percent time spent by the CPU waiting for I/O operations to complete.",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"iowait\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Mem Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "File System",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")\r\n  |> filter(fn: (r) => r[\"hostname\"] == \"Glances\")\r\n  |> filter(fn: (r) => r[\"mnt_point\"] == \"/etc/hostname\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "description": "CPU Temperature",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"label\"] == \"cpu_thermal 0\")"
    }
   ]
  },
  {
   "title": "WiFi Signal",
   "type": "gauge",
   "description": "In decibels, -30 is fantastic, -80 is unusable",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "   from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wifi\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"quality_level\")"
    }
   ]
  },
  { "title": "System Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "CPU % usage ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "   from(bucket: \"my_bucket\")\r\n  |> range(start: -12h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")"
    }
   ]
  },
  {
   "title": "MEM %",
   "type": "timeseries",
   "description": "Memory Usage",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -12h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "table",
   "description": "user: percent time spent in user space. User CPU time is the time spent on the processor running your program’s code (or code in libraries).\n\nsystem: percent time spent in kernel space. System CPU time is the time spent running code in the Operating System kernel.\n\nidle: percent of CPU used by any program. Every program or task that runs on a computer system occupies a certain amount of processing time on the CPU. If the CPU has completed all tasks it is idle.",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 18 },
   "targets": [
    {
     "query": "// Query for min1 data with label\r\nu = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"user\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"user\")\r\n  |> set(key: \"order\", value: \"1\")\r\n\r\n// Query for min5 data with label\r\nsystem = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"system\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"system\")\r\n  |> set(key: \"order\", value: \"2\")\r\n\r\n// Query for min15 data with label\r\nidle = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"idle\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"idle\")\r\n  |> set(key: \"order\", value: \"3\")\r\n\r\n// Combine all three queries using `union()`\r\nunion(tables: [u, system, idle])"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "table",
   "description": "total: total physical memory available.\n\nused: memory used, calculated differently depending on the platform and designed for informational purposes only. It’s compute as following:\n\nused memory = total - free (with free = available + buffers + cached)\n\nfree: memory not being used at all (zeroed) that is readily available; note that this doesn’t reflect the actual memory available (use ‘available’ instead).",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "total = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> set(key: \"label\", value: \"total\")\r\n  |> set(key: \"order\", value: \"1\")\r\n  |> last()\r\n  \r\nused = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> set(key: \"label\", value: \"used\")\r\n  |> set(key: \"order\", value: \"2\")\r\n  |> last()\r\n  \r\nfree = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\r\n  |> set(key: \"label\", value: \"free\")\r\n  |> set(key: \"order\", value: \"3\")\r\n  |> last()\r\n  \r\nunion(tables: [total, used, free])"
    }
   ]
  },
  {
   "title": "memswap",
   "type": "table",
   "description": "swap space is a reserved area on a storage device (such as a hard disk or SSD) that acts as virtual memory when the physical RAM is full",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "total = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> set(key: \"label\", value: \"total\")\r\n  |> set(key: \"order\", value: \"1\")\r\n  |> last()\r\n  \r\nused = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> set(key: \"label\", value: \"used\")\r\n  |> set(key: \"order\", value: \"2\")\r\n  |> last()\r\n  \r\nfree = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memswap\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\r\n  |> set(key: \"label\", value: \"free\")\r\n  |> set(key: \"order\", value: \"3\")\r\n  |> last()\r\n  \r\nunion(tables: [total, used, free])"
    }
   ]
  },
  {
   "title": "FS",
   "type": "table",
   "description": "The used and total file system disk space.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "total = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"size\")\r\n  |> set(key: \"label\", value: \"total size\")\r\n  |> set(key: \"order\", value: \"1\")\r\n  |> last()\r\n  \r\nused = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> set(key: \"label\", value: \"used\")\r\n  |> set(key: \"order\", value: \"2\")\r\n  |> last()\r\n  \r\nfree = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)  // Select data from the last hour\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fs\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")\r\n  |> set(key: \"label\", value: \"free\")\r\n  |> set(key: \"order\", value: \"3\")\r\n  |> last()\r\n  \r\nunion(tables: [total, used, free])"
    }
   ]
  },
  {
   "title": "Load",
   "type": "table",
   "description": "Average sum of the number of processes waiting in the run-queue plus the number currently executing over 1, 5, and 15 minutes time periods",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 18 },
   "targets": [
    {
     "query": "// Query for min1 data with label\r\nmin1 = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"min1\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"1 min\")\r\n  |> set(key: \"order\", value: \"1\")\r\n\r\n// Query for min5 data with label\r\nmin5 = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"min5\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"5 min\")\r\n  |> set(key: \"order\", value: \"2\")\r\n\r\n// Query for min15 data with label\r\nmin15 = from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"load\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"min15\")\r\n  |> last()\r\n  |> set(key: \"label\", value: \"15 min\")\r\n  |> set(key: \"order\", value: \"3\")\r\n\r\n// Combine all three queries using `union()`\r\nunion(tables: [min1, min5, min15])\r\n  |> sort(columns: [\"label\"])  // Sort the rows based on the label\r\n"
    }
   ]
  },
  { "title": "Docker Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"containers\")\r\n  |> last()\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  }
 ]
}