# Use an official Nginx image as a base image
FROM nginx:alpine

# Copy the templated HTML file into the appropriate location for Nginx
COPY main.html /usr/share/nginx/html/index.html

# Copy the icons directory into the appropriate location for Nginx
COPY icons /usr/share/nginx/html/icons

# Expose port 80 so the server can be accessed externally
EXPOSE 80
