services:
  subsonic:
    image: hurricane/subsonic
    container_name: subsonic
    restart: unless-stopped
    platform: linux/arm64/v8
    volumes:
      - /mnt/subsonic/config:/config # Persist Subsonic configuration
      - /media/HD_1/Media/Music/Scott:/music # Path to your music files
    ports:
      - "4040:4040" # Subsonic web interface port
      - "4443:4443" # Subsonic HTTPS port
      - "6767:6767" # Subsonic streaming port
