# Create directories required by komga
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /mnt/airsonic/config

- name: Create and start Subsonic
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/airsonic_compose
  register: output
