# Create directories required by arr's
- name: Create directorys for arr stack storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /media/{{ mount_point }}/Media/Metadata/prowlarr
    - /media/{{ mount_point }}/Media/Metadata/sonarr
    - /media/{{ mount_point }}/Media/Metadata/radarr
    - /media/{{ mount_point }}/Media/Metadata/bazarr
    - /media/{{ mount_point }}/Media/Movies
    - /media/{{ mount_point }}/Media/TV Shows
    - /media/{{ mount_point }}/Media/Metadata/qbittorrent
    - /media/{{ mount_point }}/Media/Metadata/qbittorrent/appdata
    - /media/{{ mount_point }}/Media/Downloads
    - /media/{{ mount_point }}/Media/Downloads/completed
    - /media/{{ mount_point }}/Media/Downloads/watch


- name: Template the docker-compose file
  template:
    src: arr_stack_compose/docker-compose.yml.j2
    dest: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/arr_stack_compose/docker-compose.yml

# Run arr_stack docker compose
- name: Create and start arr stack
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/arr_stack_compose
  register: output