# Create directories required by grafana
#- name: Create directory for grafana storage
#  become: true
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0777'
#  loop:
#    - /media/HD_1/Media/Pictures/immich

# Copy enviroment vars required by docker compose file to host
- name: Copy grafana .env file
  ansible.builtin.copy:
    src: grafana_compose/.env
    dest: /home/scott/NAS_drive/ansible/tasks/grafana_compose/.env
  register: output

- name: Synchronize grafana-provisioning directory and its contents
  ansible.builtin.synchronize:
    src: grafana_compose/grafana-provisioning/
    dest: /home/scott/NAS_drive/ansible/tasks/grafana_compose/grafana-provisioning/
    mode: push
    register: output

# Run Immich docker compose
- name: Create and start Grafana
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/grafana_compose
  register: output