# Create directories required by grafana
- name: Create directory for grafana storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /home/scott/NAS_drive/ansible/tasks/grafana_compose/grafana-provisioning ####################

# Copy enviroment vars required by docker compose file to host
- name: Copy grafana .env file
  ansible.builtin.copy:
    src: grafana_compose/.env
    dest: /home/scott/NAS_drive/ansible/tasks/grafana_compose/.env
  register: output

- name: Debug the source path
  debug:
    msg: "The source directory is: {{ ansible_env.PWD }}/grafana_compose/grafana-provisioning"


- name: Synchronize grafana-provisioning directory and its contents
  ansible.builtin.synchronize:
    src: /home/scott/NAS_drive/ansible/tasks/grafana_compose/grafana-provisioning/
    dest: /home/scott/NAS_drive/ansible/tasks/grafana_compose/grafana-provisioning/
    mode: push

# Run Immich docker compose
- name: Create and start Grafana
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/grafana_compose
  register: output