# Create directories required by immich
- name: Create directory for immich storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /media/{{ mount_point }}/Media/Pictures/immich

- name: Create the .env file from template
  template:
    src: env_templates/immich.env.j2
    dest: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/immich_compose/.env

# Run Immich docker compose
- name: Create and start Immich
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/immich_compose
  register: output