# Create directories required by immich
- name: Create directory for immich storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /media/HD_1/Media/Pictures/immich

# Copy enviroment vars required by docker compose file to host
#- name: Copy .env file
#  ansible.builtin.copy:
#    src: immich_compose/.env
#    dest: /home/scott/NAS_drive/ansible/tasks/immich_compose/.env

- name: Create the .env file from template
  template:
    src: /env_templates/immich.env.j2
    dest: /home/scott/NAS_drive/ansible/tasks/immich_compose/.env

# Run Immich docker compose
- name: Create and start Immich
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/immich_compose
  register: output