- name: Pull MariaDB Docker image
  become: true
  community.docker.docker_image:
    name: mariadb:latest
    source: pull

- name: Start MariaDB Docker container
  become: true
  community.docker.docker_container:
    name: mariadb
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    state: started
    restart_policy: always
    volumes:
      - "db:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
    #ports:
    #  - "3306:3306"

