#- name: Run glances in webserver mode
#  ansible.builtin.shell:
#    cmd: |
#      docker run -d --name=Glances --hostname=Glances --restart="always" --network=host -e GLANCES_OPT="-w" -v glances_config:/glances/conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host docker.io/nicolargo/glances
#  become: true


#- name: Run Glances container
#  docker_container:
#    name: Glances
#    hostname: Glances
#    image: docker.io/nicolargo/glances
#    restart_policy: always
#    env:
#      GLANCES_OPT: "-w"
#    volumes:
#      - glances_config:/glances/conf
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    network_mode: host
#    pid_mode: host

- name: Create and start Glance and InfluxDB
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/test_compose
  register: output