- name: Run Glances container
  become: true
  docker_container:
    name: Glances
    hostname: Glances
    image: docker.io/nicolargo/glances
    restart_policy: always
    env:
      GLANCES_OPT: "-w"
    volumes:
      - glances_config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    pid_mode: host

    
