
#- name: Ensure /etc/glances directory exists
#  become: true
#  ansible.builtin.file:
#    path: /etc/glances
#    state: directory
#
#- name: Create glances.conf file
#  become: true
#  ansible.builtin.file:
#    path: /etc/glances/glances.conf
#    state: touch
#
#- name: Add content to glances.conf
#  become: true
#  ansible.builtin.blockinfile:
#    path: /etc/glances/glances.conf
#    block: |
#      [influxdb2]
#      host=localhost
#      port=8086
#      protocol=http
#      org=nicolargo
#      bucket=glances
#      token=EjFUTWe8U-MIseEAkaVIgVnej_TrnbdvEcRkaB1imstW7gapSqy6_6-8XD-yd51V0zUUpDy-kAdVD1purDLuxA==
#      # Set the interval between two exports (in seconds)
#      # If the interval is set to 0, the Glances refresh time is used (default behavor)
#      #interval=0
#      # Prefix will be added for all measurement name
#      # Ex: prefix=foo
#      #     => foo.cpu
#      #     => foo.mem
#      # You can also use dynamic values
#      #prefix=foo
#      # Following tags will be added for all measurements
#      # You can also use dynamic values.
#      # Note: hostname is always added as a tag
#      #tags=foo:bar,spam:eggs,domain:`domainname`
#
#- name: Create and start Glance and InfluxDB
#  become: true
#  community.docker.docker_compose_v2:
#    project_src: /home/scott/NAS_drive/ansible/tasks/test_compose
#  register: output
#

- name: Run Glances container
  docker_container:
    name: Glances
    hostname: Glances
    image: docker.io/nicolargo/glances
    restart_policy: always
    env:
      GLANCES_OPT: "-w"
    volumes:
      - glances_config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: host
    pid_mode: host

    
