#- name: Nextcloud with MariaDB db
#  become: true
#  community.docker.docker_compose_v2:
#    project_name: nextcloud
#    definition:
#      version: '3'
#
#      volumes:
#        nextcloud:
#          driver: local
#        db:
#          driver: local
#
#      services:
#        db:
#          image: mariadb:latest
#          command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
#          restart: always
#          volumes:
#            - db:/var/lib/mysql
#          container_name: mariadb
#          #environment:
#          #  - MYSQL_ROOT_PASSWORD=ABC123
#          #  - MYSQL_PASSWORD=DEF456
#          #  - MYSQL_DATABASE=nextcloud
#          #  - MYSQL_USER=nextcloud
#          environment:
#             - "MYSQL_ROOT_PASSWORD={{ MYSQL_ROOT_PASSWORD }}"
#             - "MYSQL_DATABASE={{ MYSQL_DATABASE }}"
#             - "MYSQL_USER={{ MYSQL_USER }}"
#             - "MYSQL_PASSWORD={{ MYSQL_PASSWORD }}"
#          networks:
#            - nextcloud_network
#
#        app:
#          image: nextcloud:latest
#          ports:
#            - "8000:80"
#          container_name: nextcloud
#          volumes:
#            - nextcloud:/var/www/html
#            - "/media/HD_1:/media/HD_1"
#          restart: always
#          networks:
#            - nextcloud_network
#
#      networks:
#        nextcloud_network:
#          driver: bridge

- name: Create and start Nextcloud and mariaDB
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/docker_compose
  register: output
