#- name: Nextcloud with MariaDB db
#  community.docker.docker_compose_v2:
#    project_name: nextcloud
#    definition:
#      version: '3'
#
#      volumes:
#        nextcloud:
#          driver: local
#        db:
#          driver: local
#
#      services:
#        db:
#          image: mariadb:latest
#          command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
#          restart: always
#          volumes:
#            - db:/var/lib/mysql
#          container_name: mariadb
#          environment:
#            - MYSQL_ROOT_PASSWORD=ABC123
#            - MYSQL_PASSWORD=DEF456
#            - MYSQL_DATABASE=nextcloud
#            - MYSQL_USER=nextcloud
#          networks:
#            - nextcloud_network
#
#        app:
#          image: nextcloud:latest
#          ports:
#            - "8000:80"
#          container_name: nextcloud
#          volumes:
#            - nextcloud:/var/www/html
#          restart: always
#          networks:
#            - nextcloud_network
#
#      networks:
#        nextcloud_network:
#          driver: bridge

- name: Create and start services
  #community.docker.docker_compose_v2:
  #  project_src: docker_compose
  #  #action: up
  #register: output
  #docker-compose up
  become: True
  ansible.builtin.shell:
    cmd: |
     pwd
     ls
    chdir: /home/scott/NAS_drive/ansible/tasks