- name: Install python3-venv package
  ansible.builtin.package:
    name: python3-venv
    state: present

- name: Create virtual environment
  ansible.builtin.command: 
   cmd: |
    python -m venv /home/{{ ansible_user }}/NAS_drive/venv
  args:
   creates: /home/{{ ansible_user }}/NAS_drive/venv

#- name: Activate virtual environment
#  ansible.builtin.command: 
#   cmd: |
#    source venv/bin/activate
#   chdir: /home/{{ ansible_user }}/NAS_drive

- name: Install Python requirements
  ansible.builtin.pip:
   virtualenv: /home/{{ ansible_user }}/NAS_drive/venv
   requirements: /home/{{ ansible_user }}/NAS_drive/requirements.txt