# Create directories required by Tandoor
- name: Create directory for tandoor storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /media/HD_1/Media/Recipes
    - /media/HD_1/Media/Recipes/tandoor
    - /media/HD_1/Media/Recipes/tandoor/postgres
    - /media/HD_1/Media/Recipes/tandoor/mediafiles

- name: Create the .env file from template
  template:
    src: /env_templates/tandoor.env.j2
    dest: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/tandoor_compose/.env

# Run Tandoor docker compose
- name: Create and start Tandoor
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/tandoor_compose
  register: output