# Create directories required by immich
#- name: Create directory for tamdoor storage
#  become: true
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0777'
#  loop:
#    - /media/HD_1/Media/Pictures/immich

# Copy enviroment vars required by docker compose file to host
- name: Copy .env file
  ansible.builtin.copy:
    src: tandoor_compose/.env
    dest: /home/scott/NAS_drive/ansible/tasks/tandoor_compose/.env

# Run Tandoor docker compose
- name: Create and start Tandoor
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/scott/NAS_drive/ansible/tasks/tandoor_compose
  register: output