version: "3.7"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9080
      - TORRENTING_PORT=6881
    volumes:
      - /media/HD_1/Media/Metadata/qbittorrent/appdata:/config
      - /media/HD_1/Media/Downloads/completed:/downloads #optional
    ports:
      - 9080:9080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - bridge_network


  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/HD_1/Media/Metadata/radarr:/config
      - /media/HD_1/Media/Movies:/movies
      - /media/HD_1/Media/Downloads/completed:/downloads
    networks:
      - bridge_network

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/HD_1/Media/Metadata/sonarr:/config
      - /media/HD_1/Media/TV Shows:/tv
      - /media/HD_1/Media/Downloads/completed:/downloads
    networks:
      - bridge_network

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/HD_1/Media/Metadata/prowlarr:/config
      - /media/HD_1/Media/Downloads/watch:/downloads
    networks:
      - bridge_network

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/HD_1/Media/Metadata/bazarr:/config
      - /media/HD_1/Media/Movies:/movies
      - /media/HD_1/Media/TV Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge
