services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /media/HD_1/Media/metadata/ampache/config:/var/www/config #/mnt/ampache/config:/var/www/config
      - /media/HD_1/Media/metadata/ampache/log:/var/log/ampache #/mnt/ampache/log:/var/log/ampache
      - /media/HD_1/Media/metadata/ampache/mysql:/var/lib/mysql #/mnt/ampache/mysql:/var/lib/mysql
      - /media/HD_1/Media/Music:/media